package com.redhat.vcs.model;

public enum VaccineBrand {
    PFIZER, MODERNA, JOHNSON, JANSSEN, ASTRAZENECA, NOVAVAX,COMIRNATY,COVAXIN,COVOVAX,COVISHIELD,OXFORD,SINOPHARM,SPIKEVAX,SPUTNIK,VAXZEVRIA,SINOVAC_CORONAVAC;
}
